FROM ubuntu:16.04

# Install prerequisites
RUN apt update && \
	apt-get install -y build-essential wget unzip python2.7 \
	python-dev git python-pip curl autoconf autogen libssl-dev \
	ncbi-blast+ software-properties-common

# install Java
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
	add-apt-repository -y ppa:webupd8team/java && \
	apt-get update && \
	apt-get install -y oracle-java8-installer && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/oracle-jdk8-installer

# install the AWS CLI
RUN pip install awscli --upgrade --user
ENV PATH="/root/.local/bin:$PATH"

# install kraken2
RUN cd /usr/ && \
	wget http://github.com/DerrickWood/kraken2/archive/v2.0.7-beta.tar.gz && \
	tar xzvf v2.0.7-beta.tar.gz && \
	cd kraken2-2.0.7-beta && \
	./install_kraken2.sh /usr/local/bin/kraken2-v2.0.7 && \
	ln -s /usr/local/bin/kraken2-v2.0.7/kraken2* /usr/local/bin/ && \
	kraken2-build -h

# install bazam
RUN cd /bin/ && \
	git clone https://github.com/ssadedin/bazam.git && \
	cd bazam && \
	git submodule update --init --recursive && \
	./gradlew clean jar

